resources:

- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/starkandwayne/concourse-tutorial.git

- name: resource-gist
  type: git
  source:
    branch: master
    uri: {{gist-url}}
    private_key: {{github-private-key}}

- name: resource-version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri-bump-semver}}
    branch: version
    file: version
    private_key: {{github-private-key}}

jobs:

- name: job-bump-date
  serial: true
  plan:
  - get: resource-tutorial
  - get: resource-gist
  - task: bump-timestamp-file
    file: resource-tutorial/12_publishing_outputs/bump-timestamp-file.yml
  - put: resource-gist
    params: {repository: updated-gist}

- name: job-show-date
  plan:
  - get: resource-tutorial
  - get: resource-gist
    passed: [job-bump-date]
    trigger: true
  - task: show-date
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: resource-gist
      run:
        path: cat
        args: [resource-gist/bumpme]

- name: job-versioning
  public: true
  serial: true
  plan:
  - get: resource-version
    params: {pre: rc}
  - task: display-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: resource-version
      run:
        path: cat
        args: [resource-version/number]
  - put: resource-version
    params: {file: resource-version/number}
- name: job-bump-patch
  public: true
  serial: true
  plan:
  - get: resource-version
    params: {bump: patch}
  - task: display-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: resource-version
      run:
        path: cat
        args: [resource-version/number]
  - put: resource-version
    params: {file: resource-version/number}
